---
title: "Homework 0"
format: html
editor: visual
---

## Computation

The following message shows solutions of the given equation: ax\^2 + bx + c = 0.

**NOTE**: The message presented will be different for numbers of real roots available.

```{r}
#| echo: false
a <- 1 
b <- 3 
c <- 2
x <- -10:10 
fx <- a*x^2 + b*x + c
if ((b^2 - 4*a*c) < 0){
  x1 = NaN
  x2 = NaN
} else {
  x1 <- (-b + sqrt(b^2 - 4*a*c)) / (2*a)
  x2 <- (-b - sqrt(b^2 - 4*a*c)) / (2*a)
}

if (is.nan(x1) & is.nan(x2)){
  cat("There is no solution to the given equation")
} else if (is.nan(x1) | is.nan(x2)){
  sol <- if (is.nan(x1)) x2 else x1
  cat("The only solution to the given equation is:", sol)
} else {
  if (x1 == x2) cat("The only solution to the given equation is: " , x1)
  else cat("Solutions to the given equation are :", x1, " and ", x2)
}
```

## Proofing Plot

In order to proof the previous result. A plot of the function is presented below and the dotted line is f(x) = 0 so that the x-intersection(s) are presented in the plot.

```{r}
#| echo: false

plot(x, fx, type="l")
abline(h=0, lty=2)
```
